import type { Metadata } from "next";
import "./globals.css";
import { Heebo } from "next/font/google";

import { Navbar } from "./_components/navbar";
import { Footer } from "./_components/footer";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const heebo = Heebo({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-dvh flex flex-col", heebo.className)}>
        <Navbar />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
